import { assertValidCommerceTemplate } from '../../validate'

export const partyRentals = assertValidCommerceTemplate({
  id: 'events.party-rentals',
  version: 1,
  status: 'active',
  domain: 'events-hospitality',
  industry: 'Party Rentals',
  title: 'Party Rentals',
  description: 'Finite event-rental inventory configured around item quantities, an event window, delivery or pickup, site access, availability, and merchant-authored payment terms.',
  primaryArchetype: 'inventory-rental',
  secondaryArchetypes: ['delivery-service', 'configurable-appointment'],
  matchHints: {
    industries: ['Party Rentals', 'Event Rentals', 'Tent Rentals', 'Table and Chair Rentals'],
    keywords: ['party rentals', 'event rentals', 'tent rental', 'table rental', 'chair rental'],
    offerTerms: ['tables and chairs', 'rental package', 'tent package', 'delivery and setup'],
  },
  customerJobs: [
    'Reserve the right quantities of event equipment for a specific window and coordinate pickup, delivery, setup, and return without assuming stock is available.',
  ],
  customerIntents: [
    { id: 'chairs-tables', text: 'I need to rent 80 chairs and 10 tables for a party Saturday.' },
    { id: 'tent-package', text: 'Find a tent, table, and chair rental package for an outdoor wedding.' },
    { id: 'delivery-setup', text: 'Rent party equipment with delivery and setup for my event.' },
  ],
  offerBlueprints: [
    {
      key: 'inventory-backed-rental',
      name: 'Inventory-Backed Rental',
      kind: 'product',
      description: 'A merchant-authored rental inventory configuration that requires an authoritative availability check and hold before checkout.',
      commonConfiguration: ['rental items', 'item quantities', 'event window', 'delivery or pickup', 'service location'],
    },
    {
      key: 'delivered-event-package',
      name: 'Delivered Event Package',
      kind: 'service',
      description: 'A merchant-confirmed fixed-total package with delivery, setup, return coordination, and an explicitly staged payment schedule when offered.',
      commonConfiguration: ['package scope', 'event window', 'site access', 'delivery and setup', 'return window'],
    },
  ],
  requiredFacts: [
    {
      key: 'rental-items',
      label: 'Rental items',
      description: 'The exact merchant-authored catalog items or package requested by the buyer.',
      importance: 'required',
      scope: 'customer-request',
      valueType: 'multi-select',
      ask: 'Which rental items or package does the event require?',
      why: 'A rental request cannot be priced or checked against inventory without an exact item configuration.',
    },
    {
      key: 'item-quantities',
      label: 'Item quantities',
      description: 'The requested quantity for each selected rental item.',
      importance: 'required',
      scope: 'customer-request',
      valueType: 'quantity',
      ask: 'How many units of each rental item are needed?',
      why: 'Finite availability and unit pricing depend on canonical requested quantities.',
    },
    {
      key: 'event-window',
      label: 'Event and rental window',
      description: 'The event timing plus the required possession, delivery, pickup, or return window.',
      importance: 'required',
      scope: 'customer-request',
      valueType: 'date-time',
      ask: 'What is the event date and what delivery, pickup, or return window is required?',
      why: 'Reusable inventory is available only for a specific merchant-authored window.',
    },
    {
      key: 'service-location',
      label: 'Service location',
      description: 'The event or handoff location used to validate fulfillment coverage.',
      importance: 'required',
      scope: 'customer-request',
      valueType: 'location',
      ask: 'Where will the rental be delivered, set up, or picked up?',
      why: 'Delivery eligibility, logistics, and any location-dependent charge require a real address or service area.',
    },
    {
      key: 'availability-source',
      label: 'Availability authority',
      description: 'The merchant-authored inventory pool or external system authoritative for availability.',
      importance: 'required',
      scope: 'offer',
      valueType: 'string',
      ask: 'What published inventory source is authoritative for this rental offer?',
      why: 'Nexez must check or hold real merchant inventory instead of inferring availability from the template.',
    },
    {
      key: 'price-logic',
      label: 'Pricing logic',
      description: 'The merchant-authored unit, package, delivery, setup, and payment calculation.',
      importance: 'required',
      scope: 'offer',
      valueType: 'money',
      ask: 'How are item quantities, rental duration, delivery, setup, and payment stages priced?',
      why: 'A valid checkout needs an authoritative total or an explicit quote path.',
    },
  ],
  qualityFacts: [
    {
      key: 'fulfillment-mode',
      label: 'Pickup, delivery, and setup',
      description: 'The supported handoff, setup, teardown, and return options.',
      importance: 'quality',
      scope: 'customer-request',
      valueType: 'enum',
      ask: 'Does the buyer need pickup, delivery, setup, teardown, or a combination?',
      why: 'The requested logistics can change eligibility, timing, and price.',
    },
    {
      key: 'site-access',
      label: 'Site access',
      description: 'Loading, stairs, elevator, surface, power, anchoring, or venue restrictions that affect fulfillment.',
      importance: 'quality',
      scope: 'customer-request',
      valueType: 'multi-select',
      ask: 'Are there any access, loading, surface, power, anchoring, or venue restrictions?',
      why: 'Merchant-authored rules may require review when the site cannot support normal delivery or setup.',
    },
    {
      key: 'damage-security-terms',
      label: 'Damage and security terms',
      description: 'The merchant-authored damage waiver, loss policy, or refundable security terms, if any.',
      importance: 'quality',
      scope: 'offer',
      valueType: 'string',
      ask: 'What damage, loss, waiver, or refundable security terms apply?',
      why: 'These obligations must be disclosed as merchant policy and must not be confused with a Nexez-held deposit.',
    },
    {
      key: 'cancellation-policy',
      label: 'Cancellation policy',
      description: 'The merchant-authored cancellation, rescheduling, and weather policy.',
      importance: 'quality',
      scope: 'offer',
      valueType: 'string',
      ask: 'What cancellation, rescheduling, or weather policy applies?',
      why: 'Time-bound reusable inventory often has material cancellation constraints.',
    },
  ],
  opportunityFacts: [
    {
      key: 'add-ons',
      label: 'Rental add-ons',
      description: 'Optional linens, lighting, decor, setup, teardown, or related merchant-authored items.',
      importance: 'opportunity',
      scope: 'offer',
      valueType: 'multi-select',
      ask: 'Which related rental items or services can buyers add?',
      why: 'Structured add-ons can complete the event configuration without changing the merchant’s inventory truth.',
    },
  ],
  pricingModes: ['unit', 'fixed', 'quote'],
  fulfillmentModes: ['pickup-delivery', 'delivery'],
  schedulingModes: ['date-window'],
  paymentModes: ['full-checkout', 'deposit-balance'],
  capabilityTags: [
    'INVENTORY',
    'DELIVERY',
    'SCHEDULED',
    'CAPACITY_LIMITED',
    'DEPOSIT',
    'CONFIGURABLE',
    'ADD_ONS',
    'AVAILABILITY',
    'UNIT_PRICING',
    'CUSTOM_INTAKE',
  ],
  relatedTemplates: [
    { templateId: 'events.event-planning', relation: 'often-purchased-with', why: 'Event planners may coordinate rental selection and logistics.' },
    { templateId: 'events.event-catering', relation: 'often-purchased-with', why: 'Catering configurations often depend on tables, chairs, linens, or serving equipment.' },
  ],
  evals: [
    {
      id: 'events.party-rentals.direct',
      difficulty: 'direct',
      request: 'I need to rent 80 chairs and 10 tables for a party Saturday.',
      expected: {
        templateId: 'events.party-rentals',
        requiredFactKeys: ['rental-items', 'item-quantities', 'event-window', 'service-location', 'availability-source', 'price-logic'],
        capabilityTags: ['INVENTORY', 'CAPACITY_LIMITED', 'SCHEDULED', 'UNIT_PRICING'],
        mustNot: ['invent inventory availability', 'invent a rental price'],
      },
    },
    {
      id: 'events.party-rentals.adversarial',
      difficulty: 'adversarial',
      request: 'Deliver a tent, tables, and chairs to an outdoor wedding this weekend and guarantee setup before guests arrive.',
      expected: {
        templateId: 'events.party-rentals',
        requiredFactKeys: ['rental-items', 'item-quantities', 'event-window', 'service-location', 'availability-source', 'price-logic'],
        capabilityTags: ['INVENTORY', 'DELIVERY', 'CONFIGURABLE', 'AVAILABILITY', 'CUSTOM_INTAKE'],
        mustNot: ['guarantee delivery or setup', 'invent damage or security terms'],
      },
    },
  ],
  exampleListing: {
    exampleOnly: true,
    disclaimer: 'Nexez example template - not a real provider or a claim of rental inventory, availability, delivery coverage, price, or booking. Merchant-specific facts must be confirmed before publishing.',
    title: 'Party Rentals - Nexez Example',
    description: 'Example of a finite-inventory event rental that checks exact quantities and timing against a real merchant before checkout.',
    offers: [
      { name: 'Inventory-Backed Rental', description: 'Configure items, quantities, event window, location, and handoff method before checking merchant-authored availability.' },
      { name: 'Delivered Event Package', description: 'Configure package scope and logistics before requesting a merchant-confirmed total and payment schedule.' },
    ],
    tryAsking: [
      'Rent 80 chairs and 10 tables for Saturday.',
      'I need a tent package for an outdoor wedding.',
      'Party rentals with delivery and setup for my event.',
    ],
  },
})
