import { candidate, score, type CommerceCurationCandidate } from './types'

export const automotiveCurationCandidates: CommerceCurationCandidate[] = [
  candidate(10, 'automotive.mobile-auto-detailing', 'Mobile Auto Detailing', 'automotive-mobile', 'mobile-service', 'pilot-active', 'Configurable mobile service with vehicle class, package, condition, location, and deterministic modifiers.', ['MOBILE', 'SERVICE_AREA', 'SCHEDULED', 'CONFIGURABLE', 'ADD_ONS', 'TRAVEL_FEE', 'CUSTOM_INTAKE', 'AVAILABILITY'], ['structured-modifiers', 'customer-requirements', 'multi-unit-booking'], score(5, 5, 5, 5, 5, 5, 5, 5, 4, 5)),
  candidate(11, 'automotive.interior-detail', 'Interior Detail', 'automotive-mobile', 'configurable-appointment', 'replacement-review', 'Condition-heavy vehicle interior work emphasizing contamination, asset condition, and add-on pricing.', ['SCHEDULED', 'CONFIGURABLE', 'ADD_ONS', 'CUSTOM_INTAKE', 'MOBILE'], ['structured-modifiers', 'customer-requirements'], score(5, 4, 5, 2, 5, 4, 3, 3, 3, 3)),
  candidate(12, 'automotive.ceramic-coating', 'Ceramic Coating', 'automotive-mobile', 'package-program', 'retain', 'High-ticket vehicle treatment with inspection, prep stages, package tiers, warranties, and deposits.', ['QUOTE_REQUIRED', 'CONFIGURABLE', 'SCHEDULED', 'DEPOSIT', 'CUSTOM_INTAKE', 'CUSTOMER_ASSETS'], ['inspection-first', 'milestones', 'document-requirements'], score(4, 5, 5, 5, 5, 4, 5, 5, 4, 5)),
  candidate(13, 'automotive.mobile-brake-service', 'Mobile Brake Service', 'automotive-mobile', 'mobile-service', 'retain', 'Mobile repair with vehicle fitment, parts uncertainty, safety constraints, and conditional quoting.', ['MOBILE', 'SERVICE_AREA', 'SCHEDULED', 'CUSTOM_INTAKE', 'QUOTE_REQUIRED', 'AVAILABILITY'], ['regulated-qualification', 'customer-requirements', 'conditional-fulfillment'], score(5, 5, 5, 5, 5, 5, 5, 5, 4, 5)),
  candidate(14, 'automotive.vehicle-diagnostic', 'Vehicle Diagnostic', 'automotive-mobile', 'consultation-first', 'retain', 'Diagnostic purchase that gates later repair decisions and separates paid diagnosis from uncertain remediation.', ['FIXED_PRICE', 'SCHEDULED', 'CUSTOM_INTAKE', 'MOBILE'], ['inspection-first', 'customer-requirements'], score(5, 5, 5, 5, 5, 5, 4, 5, 5, 5)),
  candidate(15, 'automotive.pre-purchase-inspection', 'Pre-Purchase Inspection', 'automotive-mobile', 'fixed-appointment', 'retain', 'Asset inspection with location coordination, report deliverable, deadlines, and buyer-seller handoff.', ['FIXED_PRICE', 'SCHEDULED', 'SERVICE_AREA', 'MOBILE', 'CUSTOM_INTAKE', 'CUSTOMER_ASSETS'], ['document-requirements', 'customer-requirements', 'conditional-fulfillment'], score(5, 5, 5, 5, 5, 5, 4, 4, 5, 5)),
  candidate(16, 'automotive.window-tinting', 'Window Tinting', 'automotive-mobile', 'configurable-appointment', 'retain', 'Vehicle-specific package configuration with material options, legal constraints, and warranty terms.', ['SCHEDULED', 'CONFIGURABLE', 'CUSTOM_INTAKE', 'ADD_ONS'], ['regulated-qualification', 'structured-modifiers', 'customer-requirements'], score(5, 4, 5, 4, 5, 4, 4, 4, 3, 4)),
  candidate(17, 'automotive.fleet-detailing-contract', 'Fleet Detailing Contract', 'automotive-mobile', 'contracted-service', 'retain', 'B2B recurring multi-asset service with volume tiers, SLAs, schedules, locations, and contract terms.', ['CONTRACT', 'SLA', 'RECURRING', 'UNIT_PRICING', 'SERVICE_AREA', 'MOBILE', 'CAPACITY_LIMITED', 'NEGOTIABLE'], ['recurrence-terms', 'multi-unit-booking', 'contract-terms', 'capacity-constraints'], score(4, 5, 5, 5, 5, 5, 5, 5, 5, 5)),
  candidate(18, 'automotive.mobile-tire-service', 'Mobile Tire Service', 'automotive-mobile', 'urgent-on-demand', 'retain', 'Mobile fitment and roadside scheduling with inventory, vehicle compatibility, urgency, and travel.', ['MOBILE', 'URGENT', 'SERVICE_AREA', 'SCHEDULED', 'AVAILABILITY', 'CUSTOM_INTAKE', 'INVENTORY'], ['inventory-resource', 'customer-requirements', 'conditional-fulfillment'], score(5, 5, 5, 5, 5, 5, 5, 5, 4, 5)),
]
