import { candidate, score, type CommerceCurationCandidate } from './types'

export const commercialCurationCandidates: CommerceCurationCandidate[] = [
  candidate(55, 'commercial.commercial-cleaning', 'Commercial Cleaning', 'local-commercial-operations', 'contracted-service', 'overlap-review', 'B2B facility cleaning with site scope, access or security, recurring contracts, SLAs, and multi-location pricing.', ['CONTRACT', 'SLA', 'RECURRING', 'SERVICE_AREA', 'CUSTOM_INTAKE', 'CAPACITY_LIMITED'], ['contract-terms', 'recurrence-terms', 'customer-requirements'], score(5, 5, 5, 4, 5, 5, 5, 4, 5, 5)),
  candidate(56, 'commercial.recurring-janitorial-service', 'Recurring Janitorial Service', 'local-commercial-operations', 'contracted-service', 'retain', 'Formal recurring facility operations with frequencies, staffing, checklists, SLAs, supplies, and contracts.', ['CONTRACT', 'SLA', 'RECURRING', 'SERVICE_AREA', 'CAPACITY_LIMITED', 'SUBSCRIPTION', 'CUSTOM_INTAKE'], ['contract-terms', 'recurrence-terms', 'inventory-resource', 'capacity-constraints'], score(4, 5, 5, 5, 5, 5, 5, 5, 5, 5)),
  candidate(57, 'commercial.pressure-washing', 'Pressure Washing', 'local-commercial-operations', 'mobile-service', 'retain', 'Measured mobile service with surface area, surface type, access, water constraints, travel, and unit pricing.', ['MOBILE', 'SERVICE_AREA', 'SCHEDULED', 'UNIT_PRICING', 'CUSTOM_INTAKE', 'QUOTE_REQUIRED'], ['quantity-pricing', 'customer-requirements', 'conditional-fulfillment'], score(5, 5, 5, 5, 5, 5, 5, 5, 4, 5)),
  candidate(58, 'commercial.junk-removal', 'Junk Removal', 'local-commercial-operations', 'unit-priced-service', 'retain', 'Volume or weight based mobile service with photos, item restrictions, disposal rules, access, and quote ranges.', ['MOBILE', 'SERVICE_AREA', 'QUOTE_REQUIRED', 'CUSTOMER_ASSETS', 'CUSTOM_INTAKE', 'CAPACITY_LIMITED'], ['quantity-pricing', 'document-requirements', 'regulated-qualification', 'capacity-constraints'], score(5, 5, 5, 4, 5, 5, 5, 5, 5, 5)),
  candidate(59, 'commercial.laundry-pickup-delivery', 'Laundry Pickup & Delivery', 'local-commercial-operations', 'delivery-service', 'retain', 'Pickup and delivery recurring commerce with unit pricing, route windows, turnaround, subscriptions, and item constraints.', ['DELIVERY', 'RECURRING', 'SUBSCRIPTION', 'UNIT_PRICING', 'SERVICE_AREA', 'SCHEDULED', 'CAPACITY_LIMITED'], ['route-optimization', 'recurrence-terms', 'quantity-pricing', 'capacity-constraints'], score(5, 5, 5, 5, 5, 5, 5, 5, 5, 5)),
  candidate(60, 'commercial.pest-control', 'Pest Control', 'local-commercial-operations', 'recurring-service', 'retain', 'Inspection and diagnostic service with property context, treatment plan, regulated constraints, recurrence, and warranties.', ['RECURRING', 'SCHEDULED', 'SERVICE_AREA', 'MOBILE', 'CUSTOM_INTAKE', 'QUOTE_REQUIRED'], ['regulated-qualification', 'inspection-first', 'recurrence-terms', 'conditional-fulfillment'], score(5, 5, 5, 4, 5, 5, 5, 5, 5, 5)),
  candidate(61, 'commercial.property-turnover-service', 'Property Turnover Service', 'local-commercial-operations', 'complex-project', 'overlap-review', 'Multi-service property reset combining cleaning, inspection, minor repair, supplies, deadlines, and handoff.', ['PROJECT_SCOPE', 'MULTI_PROVIDER', 'SCHEDULED', 'SERVICE_AREA', 'MOBILE', 'CUSTOM_INTAKE', 'MILESTONE'], ['multi-provider-orchestration', 'milestones', 'inventory-resource', 'conditional-fulfillment'], score(4, 5, 5, 5, 5, 5, 5, 5, 5, 5)),
  candidate(62, 'commercial.commercial-landscaping', 'Commercial Landscaping', 'local-commercial-operations', 'contracted-service', 'overlap-review', 'Recurring multi-site grounds service with seasonal scope, crews or equipment, SLAs, contracts, and capacity.', ['CONTRACT', 'SLA', 'RECURRING', 'SERVICE_AREA', 'MOBILE', 'CAPACITY_LIMITED', 'INVENTORY'], ['contract-terms', 'recurrence-terms', 'inventory-resource', 'capacity-constraints'], score(4, 5, 5, 4, 5, 4, 5, 4, 4, 5)),
  candidate(63, 'commercial.locksmith-service', 'Locksmith Service', 'local-commercial-operations', 'urgent-on-demand', 'retain', 'Urgent mobile service with proof of authorization, travel, asset type, availability, and call-out pricing.', ['URGENT', 'MOBILE', 'SERVICE_AREA', 'SCHEDULED', 'AVAILABILITY', 'CUSTOM_INTAKE', 'FIXED_PRICE'], ['regulated-qualification', 'document-requirements', 'minimum-charge', 'customer-requirements'], score(5, 5, 5, 5, 5, 5, 5, 5, 4, 5)),
]
