import { candidate, score, type CommerceCurationCandidate } from './types'

export const educationPetCurationCandidates: CommerceCurationCandidate[] = [
  candidate(46, 'education.private-tutoring', 'Private Tutoring', 'education-family-pet', 'fixed-appointment', 'pilot-active', 'Subject and learner-fit appointment with delivery mode, schedule, package structure, and recurring potential.', ['FIXED_PRICE', 'SCHEDULED', 'RECURRING', 'REMOTE', 'SERVICE_AREA', 'CUSTOM_INTAKE', 'AVAILABILITY'], ['qualification-fit', 'customer-requirements', 'recurrence-terms'], score(5, 5, 5, 5, 5, 5, 4, 4, 5, 5)),
  candidate(47, 'education.test-prep-program', 'Test Prep Program', 'education-family-pet', 'package-program', 'retain', 'Deadline-driven multi-session program with exam date, diagnostic baseline, curriculum, cadence, and package pricing.', ['SCHEDULED', 'RECURRING', 'CONFIGURABLE', 'CUSTOM_INTAKE', 'REMOTE', 'SUBSCRIPTION'], ['recurrence-terms', 'customer-requirements', 'milestones'], score(5, 5, 5, 4, 5, 5, 5, 5, 5, 5)),
  candidate(48, 'education.music-lessons', 'Music Lessons', 'education-family-pet', 'recurring-service', 'retain', 'Recurring appointment with instrument or level fit, location, cadence, package billing, and equipment constraints.', ['RECURRING', 'SCHEDULED', 'REMOTE', 'SERVICE_AREA', 'CUSTOM_INTAKE', 'SUBSCRIPTION'], ['recurrence-terms', 'inventory-resource', 'qualification-fit'], score(5, 4, 5, 4, 5, 5, 4, 4, 4, 4)),
  candidate(49, 'education.language-lessons', 'Language Lessons', 'education-family-pet', 'recurring-service', 'retain', 'Recurring remote instruction with language and level fit, cadence, goals, package structure, and time zones.', ['RECURRING', 'SCHEDULED', 'REMOTE', 'CUSTOM_INTAKE', 'SUBSCRIPTION'], ['recurrence-terms', 'qualification-fit'], score(5, 4, 5, 3, 5, 5, 3, 3, 4, 4)),
  candidate(50, 'education.college-admissions-consulting', 'College Admissions Consulting', 'education-family-pet', 'complex-project', 'retain', 'Deadline-heavy advisory project with student documents, milestones, review cycles, packages, and qualification boundaries.', ['PROJECT_SCOPE', 'MILESTONE', 'CUSTOMER_ASSETS', 'REVISION_LIMITS', 'CUSTOM_INTAKE', 'REMOTE', 'DEPOSIT'], ['document-requirements', 'milestones', 'regulated-qualification'], score(5, 5, 5, 4, 5, 5, 5, 5, 5, 5)),
  candidate(51, 'pet.dog-walking', 'Dog Walking', 'education-family-pet', 'recurring-service', 'retain', 'Recurring local service with pet profile, access instructions, cadence, geography, and multi-pet pricing.', ['RECURRING', 'SCHEDULED', 'SERVICE_AREA', 'MOBILE', 'UNIT_PRICING', 'CUSTOM_INTAKE'], ['recurrence-terms', 'multi-unit-booking', 'customer-requirements'], score(5, 4, 5, 4, 5, 4, 4, 4, 5, 4)),
  candidate(52, 'pet.pet-sitting', 'Pet Sitting', 'education-family-pet', 'package-program', 'retain', 'Date-window care with pet profiles, home access, medication instructions, overnight capacity, and emergency contacts.', ['SCHEDULED', 'SERVICE_AREA', 'MOBILE', 'CUSTOM_INTAKE', 'CAPACITY_LIMITED'], ['customer-requirements', 'capacity-constraints', 'conditional-fulfillment'], score(5, 5, 5, 4, 5, 5, 5, 5, 5, 5)),
  candidate(53, 'pet.mobile-pet-grooming', 'Mobile Pet Grooming', 'education-family-pet', 'mobile-service', 'retain', 'Mobile appointment with species, breed or size, condition, package, travel, and capacity constraints.', ['MOBILE', 'SERVICE_AREA', 'SCHEDULED', 'CONFIGURABLE', 'ADD_ONS', 'CUSTOM_INTAKE', 'AVAILABILITY'], ['customer-requirements', 'structured-modifiers', 'capacity-constraints'], score(5, 5, 5, 4, 5, 5, 4, 4, 4, 5)),
  candidate(54, 'pet.dog-training', 'Dog Training', 'education-family-pet', 'package-program', 'retain', 'Program commerce with behavioral intake, modality, recurring sessions, package milestones, and qualification boundaries.', ['RECURRING', 'SCHEDULED', 'CONFIGURABLE', 'CUSTOM_INTAKE', 'REMOTE', 'MILESTONE'], ['recurrence-terms', 'qualification-fit', 'milestones'], score(5, 5, 5, 4, 5, 5, 5, 5, 5, 5)),
]
