import { candidate, score, type CommerceCurationCandidate } from './types'

export const eventsCurationCandidates: CommerceCurationCandidate[] = [
  candidate(19, 'events.event-photography', 'Event Photography', 'events-hospitality', 'package-program', 'pilot-active', 'Time-bound creative coverage with duration, deliverables, turnaround, rights, travel, and add-ons.', ['SCHEDULED', 'SERVICE_AREA', 'MOBILE', 'CONFIGURABLE', 'ADD_ONS', 'DEPOSIT', 'LICENSING', 'TRAVEL_FEE', 'CUSTOM_INTAKE'], ['usage-rights', 'structured-modifiers', 'distance-travel-fee'], score(5, 5, 5, 4, 5, 5, 5, 5, 4, 5)),
  candidate(20, 'events.wedding-videography', 'Wedding Videography', 'events-hospitality', 'package-program', 'retain', 'Long-duration event production with packages, second shooters, deliverables, rights, deposits, and deadlines.', ['SCHEDULED', 'SERVICE_AREA', 'MOBILE', 'CONFIGURABLE', 'ADD_ONS', 'DEPOSIT', 'LICENSING', 'CUSTOMER_ASSETS'], ['milestones', 'usage-rights', 'structured-modifiers'], score(5, 5, 5, 4, 5, 5, 5, 4, 5, 5)),
  candidate(21, 'events.private-chef', 'Private Chef', 'events-hospitality', 'quote-required', 'pilot-active', 'Capacity- and dietary-constrained on-location service with guest count, menu, venue, and quote logic.', ['QUOTE_REQUIRED', 'MOBILE', 'SERVICE_AREA', 'UNIT_PRICING', 'CAPACITY_LIMITED', 'MINIMUMS', 'CUSTOM_INTAKE', 'ADD_ONS', 'DEPOSIT'], ['capacity-constraints', 'quantity-pricing', 'customer-requirements'], score(5, 5, 5, 4, 5, 5, 5, 5, 5, 5)),
  candidate(22, 'events.event-catering', 'Event Catering', 'events-hospitality', 'unit-priced-service', 'retain', 'Per-guest pricing with minimums, menu variants, staffing, delivery or service mode, deposits, and capacity.', ['UNIT_PRICING', 'CAPACITY_LIMITED', 'MINIMUMS', 'CONFIGURABLE', 'ADD_ONS', 'DEPOSIT', 'DELIVERY', 'CUSTOM_INTAKE'], ['quantity-pricing', 'capacity-constraints', 'minimum-charge', 'inventory-resource'], score(5, 5, 5, 4, 5, 5, 5, 5, 5, 5)),
  candidate(23, 'events.dj-service', 'DJ Service', 'events-hospitality', 'fixed-appointment', 'retain', 'Time-boxed event service with equipment, venue constraints, add-ons, travel, and schedule collision.', ['SCHEDULED', 'SERVICE_AREA', 'MOBILE', 'ADD_ONS', 'TRAVEL_FEE', 'AVAILABILITY'], ['inventory-resource', 'distance-travel-fee', 'structured-modifiers'], score(5, 4, 5, 4, 5, 4, 4, 4, 5, 4)),
  candidate(24, 'events.event-planning', 'Event Planning', 'events-hospitality', 'complex-project', 'retain', 'Long-running coordination with milestones, vendors, budget, approvals, and multi-provider orchestration.', ['PROJECT_SCOPE', 'MILESTONE', 'DEPOSIT', 'NEGOTIABLE', 'MULTI_PROVIDER', 'CUSTOM_INTAKE', 'CUSTOMER_ASSETS'], ['milestones', 'multi-provider-orchestration', 'document-requirements'], score(5, 5, 5, 5, 5, 5, 5, 5, 5, 5)),
  candidate(25, 'events.party-rentals', 'Party Rentals', 'events-hospitality', 'inventory-rental', 'active', 'Inventory reservation with quantities, availability, delivery windows, deposits, damage terms, and pickup.', ['INVENTORY', 'DELIVERY', 'SCHEDULED', 'CAPACITY_LIMITED', 'DEPOSIT', 'CONFIGURABLE', 'ADD_ONS', 'AVAILABILITY'], ['inventory-resource', 'capacity-constraints', 'deposit-schedule', 'conditional-fulfillment'], score(5, 5, 5, 5, 5, 5, 5, 5, 5, 5), {
    identityTerms: ['rental', 'chair', 'table', 'tent', 'linen', 'equipment'],
    contextTerms: ['party', 'event', 'chair', 'table', 'tent', 'linen', 'decor', 'equipment'],
    excludeTerms: ['bus', 'car', 'vehicle', 'vacation', 'apartment', 'house', 'home'],
    buyerDetails: ['rental items and quantities', 'event and rental window', 'delivery, setup, pickup, or return needs', 'service location', 'site access restrictions'],
  }),
  candidate(26, 'events.proposal-setup', 'Proposal Setup', 'events-hospitality', 'configurable-appointment', 'retain', 'Highly configurable one-off setup with decor inventory, location access, timing secrecy, and teardown.', ['CONFIGURABLE', 'ADD_ONS', 'INVENTORY', 'SCHEDULED', 'SERVICE_AREA', 'MOBILE', 'CUSTOM_INTAKE'], ['inventory-resource', 'structured-modifiers', 'conditional-fulfillment'], score(4, 5, 4, 5, 4, 5, 5, 5, 4, 5)),
  candidate(27, 'events.corporate-event-production', 'Corporate Event Production', 'events-hospitality', 'complex-project', 'retain', 'Multi-vendor production with equipment, staffing, SLAs, milestones, procurement, and negotiated scope.', ['PROJECT_SCOPE', 'MULTI_PROVIDER', 'MILESTONE', 'NEGOTIABLE', 'CONTRACT', 'SLA', 'INVENTORY', 'CAPACITY_LIMITED', 'DEPOSIT'], ['multi-provider-orchestration', 'inventory-resource', 'milestones', 'contract-terms'], score(4, 5, 5, 5, 5, 5, 5, 5, 5, 5)),
]
