import { candidate, score, type CommerceCurationCandidate } from './types'

export const homeCurationCandidates: CommerceCurationCandidate[] = [
  candidate(1, 'home.recurring-home-cleaning', 'Recurring Home Cleaning', 'home-property', 'recurring-service', 'pilot-active', 'Recurring configurable service with property sizing, cadence, add-ons, and repeat settlement.', ['RECURRING', 'SCHEDULED', 'SERVICE_AREA', 'CONFIGURABLE', 'ADD_ONS', 'SUBSCRIPTION', 'MOBILE', 'CUSTOM_INTAKE'], ['recurrence-terms', 'structured-modifiers', 'customer-requirements'], score(5, 5, 5, 4, 5, 5, 5, 5, 5, 4)),
  candidate(2, 'home.deep-cleaning', 'Deep Cleaning', 'home-property', 'configurable-appointment', 'overlap-review', 'Dense add-on and condition modifiers on a familiar one-time home service.', ['FIXED_PRICE', 'SCHEDULED', 'SERVICE_AREA', 'CONFIGURABLE', 'ADD_ONS', 'CUSTOM_INTAKE', 'MOBILE'], ['structured-modifiers', 'minimum-charge', 'customer-requirements'], score(5, 4, 5, 3, 5, 4, 4, 4, 5, 3)),
  candidate(3, 'home.move-out-cleaning', 'Move-Out Cleaning', 'home-property', 'configurable-appointment', 'retain', 'Deadline-bound property service with scope completeness and property handoff constraints.', ['SCHEDULED', 'SERVICE_AREA', 'CONFIGURABLE', 'ADD_ONS', 'CUSTOM_INTAKE', 'MOBILE', 'AVAILABILITY'], ['structured-modifiers', 'customer-requirements', 'conditional-fulfillment'], score(5, 5, 5, 4, 5, 5, 4, 4, 5, 4)),
  candidate(4, 'home.emergency-plumbing', 'Emergency Plumbing', 'home-property', 'urgent-on-demand', 'retain', 'Urgent diagnostic commerce where availability, call-out fees, triage, and uncertain scope matter.', ['URGENT', 'SCHEDULED', 'SERVICE_AREA', 'MOBILE', 'AVAILABILITY', 'CUSTOM_INTAKE', 'QUOTE_REQUIRED'], ['inspection-first', 'minimum-charge', 'conditional-fulfillment'], score(5, 5, 5, 5, 5, 5, 5, 5, 4, 5)),
  candidate(5, 'home.handyman-visit', 'Handyman Visit', 'home-property', 'quote-required', 'retain', 'Multi-task visit with ambiguous scope, time estimation, materials, and quote-or-hourly settlement.', ['QUOTE_REQUIRED', 'SCHEDULED', 'SERVICE_AREA', 'MOBILE', 'CUSTOM_INTAKE', 'CONFIGURABLE'], ['inspection-first', 'customer-requirements', 'minimum-charge'], score(5, 5, 5, 4, 5, 5, 4, 4, 5, 4)),
  candidate(6, 'home.lawn-care-subscription', 'Lawn Care Subscription', 'home-property', 'recurring-service', 'retain', 'Property-area recurrence with seasonal cadence, subscription terms, and mobile fulfillment.', ['RECURRING', 'SUBSCRIPTION', 'SCHEDULED', 'SERVICE_AREA', 'MOBILE', 'CONFIGURABLE'], ['recurrence-terms', 'customer-requirements', 'conditional-fulfillment'], score(5, 4, 5, 4, 5, 4, 5, 5, 4, 4)),
  candidate(7, 'home.interior-painting', 'Interior Painting', 'home-property', 'complex-project', 'retain', 'Measured project work with room or surface scope, materials, staged fulfillment, and quote logic.', ['QUOTE_REQUIRED', 'PROJECT_SCOPE', 'CUSTOM_INTAKE', 'MOBILE', 'SERVICE_AREA', 'MILESTONE', 'DEPOSIT', 'CUSTOMER_ASSETS'], ['quantity-pricing', 'milestones', 'customer-requirements'], score(5, 5, 5, 4, 5, 5, 5, 5, 5, 5)),
  candidate(8, 'home.appliance-repair', 'Appliance Repair', 'home-property', 'consultation-first', 'retain', 'Diagnostic-first repair where model identity, visit fee, parts, and conditional follow-up drive commerce.', ['SCHEDULED', 'SERVICE_AREA', 'MOBILE', 'CUSTOM_INTAKE', 'QUOTE_REQUIRED', 'AVAILABILITY'], ['inspection-first', 'customer-requirements', 'conditional-fulfillment'], score(5, 5, 5, 5, 5, 5, 5, 5, 4, 5)),
  candidate(9, 'home.moving-service', 'Moving Service', 'home-property', 'complex-project', 'retain', 'Multi-resource fulfillment with inventory volume, crews, vehicles, timing windows, travel, and deposits.', ['QUOTE_REQUIRED', 'SCHEDULED', 'SERVICE_AREA', 'MOBILE', 'CUSTOM_INTAKE', 'CAPACITY_LIMITED', 'DEPOSIT', 'TRAVEL_FEE', 'MULTI_PROVIDER'], ['inventory-resource', 'capacity-constraints', 'distance-travel-fee', 'customer-requirements'], score(5, 5, 5, 5, 5, 5, 5, 5, 5, 5)),
]
