import { candidate, score, type CommerceCurationCandidate } from './types'

export const personalCurationCandidates: CommerceCurationCandidate[] = [
  candidate(28, 'personal.barber-appointment', 'Barber Appointment', 'beauty-fitness-personal', 'fixed-appointment', 'retain', 'Simple provider-location appointment useful as a low-complexity baseline for availability and fixed price.', ['FIXED_PRICE', 'SCHEDULED', 'AVAILABILITY'], [], score(5, 3, 5, 3, 5, 4, 2, 2, 3, 3)),
  candidate(29, 'personal.hair-styling', 'Hair Styling', 'beauty-fitness-personal', 'configurable-appointment', 'overlap-review', 'Appointment configuration around style, hair attributes, duration, add-ons, and provider expertise.', ['SCHEDULED', 'CONFIGURABLE', 'ADD_ONS', 'CUSTOM_INTAKE', 'AVAILABILITY'], ['customer-requirements', 'structured-modifiers'], score(5, 4, 5, 3, 5, 5, 3, 3, 3, 4)),
  candidate(30, 'personal.mobile-makeup-artist', 'Mobile Makeup Artist', 'beauty-fitness-personal', 'mobile-service', 'retain', 'Mobile appointment with occasion, party size, location, travel, timing, and add-on configuration.', ['MOBILE', 'SERVICE_AREA', 'SCHEDULED', 'CONFIGURABLE', 'ADD_ONS', 'TRAVEL_FEE', 'CUSTOM_INTAKE'], ['multi-unit-booking', 'distance-travel-fee', 'customer-requirements'], score(5, 5, 5, 4, 5, 5, 4, 4, 5, 5)),
  candidate(31, 'personal.bridal-beauty-package', 'Bridal Beauty Package', 'beauty-fitness-personal', 'package-program', 'retain', 'Multi-person event package with trials, deposits, schedules, travel, and capacity constraints.', ['SCHEDULED', 'CONFIGURABLE', 'DEPOSIT', 'CAPACITY_LIMITED', 'MOBILE', 'SERVICE_AREA', 'ADD_ONS', 'CUSTOM_INTAKE'], ['multi-unit-booking', 'capacity-constraints', 'deposit-schedule'], score(5, 5, 5, 4, 5, 5, 5, 5, 5, 5)),
  candidate(32, 'personal.massage-session', 'Massage Session', 'beauty-fitness-personal', 'fixed-appointment', 'retain', 'Appointment commerce with modality, duration, location choice, contraindication intake, and availability.', ['FIXED_PRICE', 'SCHEDULED', 'CONFIGURABLE', 'CUSTOM_INTAKE', 'AVAILABILITY'], ['regulated-qualification', 'customer-requirements'], score(5, 4, 5, 4, 5, 5, 4, 4, 3, 4)),
  candidate(33, 'personal.personal-training', 'Personal Training', 'beauty-fitness-personal', 'recurring-service', 'retain', 'Recurring coaching with goals, assessment, package cadence, location, progress, and subscription economics.', ['RECURRING', 'SCHEDULED', 'SUBSCRIPTION', 'CUSTOM_INTAKE', 'CONFIGURABLE', 'REMOTE'], ['recurrence-terms', 'regulated-qualification', 'customer-requirements'], score(5, 5, 5, 5, 5, 5, 5, 5, 4, 5)),
  candidate(34, 'personal.private-yoga-instruction', 'Private Yoga Instruction', 'beauty-fitness-personal', 'recurring-service', 'retain', 'Individual or small-group recurring instruction with location, cadence, capacity, and skill or health context.', ['RECURRING', 'SCHEDULED', 'MOBILE', 'REMOTE', 'CAPACITY_LIMITED', 'CUSTOM_INTAKE'], ['recurrence-terms', 'capacity-constraints', 'customer-requirements'], score(4, 4, 5, 4, 5, 4, 4, 4, 4, 4)),
  candidate(35, 'personal.nutrition-coaching', 'Nutrition Coaching', 'beauty-fitness-personal', 'package-program', 'retain', 'Remote program with qualification boundaries, recurring check-ins, customer health context, and package deliverables.', ['REMOTE', 'RECURRING', 'SUBSCRIPTION', 'CUSTOM_INTAKE', 'SCHEDULED'], ['regulated-qualification', 'document-requirements', 'recurrence-terms'], score(5, 5, 5, 5, 5, 5, 5, 5, 4, 5)),
  candidate(36, 'personal.mobile-nail-service', 'Mobile Nail Service', 'beauty-fitness-personal', 'mobile-service', 'replacement-review', 'Mobile personal-care appointment with travel, package configuration, add-ons, and availability.', ['MOBILE', 'SERVICE_AREA', 'SCHEDULED', 'CONFIGURABLE', 'ADD_ONS', 'TRAVEL_FEE'], ['distance-travel-fee', 'structured-modifiers'], score(4, 4, 4, 3, 4, 4, 3, 3, 3, 4)),
]
