import { candidate, score, type CommerceCurationCandidate } from './types'

export const professionalCurationCandidates: CommerceCurationCandidate[] = [
  candidate(37, 'professional.business-strategy-session', 'Business Strategy Session', 'professional-creative-technical', 'consultation-first', 'pilot-active', 'Bounded expert consultation with topic fit, duration, price, preparation, deliverable, and scheduling.', ['FIXED_PRICE', 'SCHEDULED', 'REMOTE', 'CUSTOM_INTAKE', 'AVAILABILITY'], ['qualification-fit', 'customer-requirements'], score(5, 5, 5, 5, 5, 5, 4, 4, 5, 5)),
  candidate(38, 'professional.monthly-bookkeeping', 'Monthly Bookkeeping', 'professional-creative-technical', 'contracted-service', 'retain', 'Recurring professional service with document intake, monthly scope, account complexity, SLA, and subscription.', ['RECURRING', 'SUBSCRIPTION', 'CONTRACT', 'SLA', 'REMOTE', 'CUSTOMER_ASSETS', 'CUSTOM_INTAKE'], ['document-requirements', 'recurrence-terms', 'contract-terms'], score(5, 5, 5, 4, 5, 5, 5, 5, 5, 5)),
  candidate(39, 'professional.tax-preparation', 'Tax Preparation', 'professional-creative-technical', 'package-program', 'retain', 'Deadline- and document-driven professional service with regulated qualification, entity complexity, and secure intake.', ['SCHEDULED', 'REMOTE', 'CUSTOMER_ASSETS', 'CUSTOM_INTAKE', 'QUOTE_REQUIRED'], ['regulated-qualification', 'document-requirements', 'conditional-fulfillment'], score(5, 5, 5, 4, 5, 5, 5, 5, 5, 5)),
  candidate(40, 'professional.brand-identity-package', 'Brand Identity Package', 'professional-creative-technical', 'package-program', 'retain', 'Creative package with client assets, deliverables, revisions, licensing, approvals, and milestone payments.', ['PROJECT_SCOPE', 'CUSTOMER_ASSETS', 'REVISION_LIMITS', 'LICENSING', 'MILESTONE', 'DEPOSIT', 'CUSTOM_INTAKE'], ['milestones', 'usage-rights', 'document-requirements'], score(5, 5, 5, 4, 5, 5, 5, 5, 5, 5)),
  candidate(41, 'professional.web-design-project', 'Web Design Project', 'professional-creative-technical', 'complex-project', 'pilot-active', 'Scoped creative and technical project with client assets, revisions, timeline, milestones, and quote-required pricing.', ['QUOTE_REQUIRED', 'NEGOTIABLE', 'PROJECT_SCOPE', 'CUSTOMER_ASSETS', 'REVISION_LIMITS', 'MILESTONE', 'DEPOSIT', 'CUSTOM_INTAKE', 'REMOTE'], ['milestones', 'document-requirements', 'conditional-fulfillment'], score(5, 5, 5, 4, 5, 5, 5, 5, 5, 5)),
  candidate(42, 'professional.video-production', 'Video Production', 'professional-creative-technical', 'complex-project', 'retain', 'Production project with shoot logistics, talent or equipment, client assets, revisions, licensing, and milestones.', ['PROJECT_SCOPE', 'CUSTOMER_ASSETS', 'REVISION_LIMITS', 'LICENSING', 'MILESTONE', 'DEPOSIT', 'MULTI_PROVIDER', 'INVENTORY'], ['multi-provider-orchestration', 'inventory-resource', 'usage-rights', 'milestones'], score(5, 5, 5, 5, 5, 5, 5, 5, 5, 5)),
  candidate(43, 'professional.copywriting-package', 'Copywriting Package', 'professional-creative-technical', 'package-program', 'retain', 'Remote deliverable package with brief intake, unit counts, revisions, client assets, and usage terms.', ['REMOTE', 'PROJECT_SCOPE', 'CUSTOMER_ASSETS', 'REVISION_LIMITS', 'CONFIGURABLE', 'CUSTOM_INTAKE'], ['quantity-pricing', 'document-requirements', 'usage-rights'], score(5, 5, 5, 4, 5, 5, 4, 4, 5, 4)),
  candidate(44, 'professional.managed-it-support', 'Managed IT Support', 'professional-creative-technical', 'contracted-service', 'retain', 'Recurring B2B support with devices or users, service tiers, SLAs, onboarding, billing, and urgent incidents.', ['CONTRACT', 'SLA', 'RECURRING', 'SUBSCRIPTION', 'REMOTE', 'URGENT', 'CUSTOM_INTAKE', 'UNIT_PRICING'], ['usage-pricing', 'contract-terms', 'recurrence-terms', 'customer-requirements'], score(5, 5, 5, 5, 5, 5, 5, 5, 5, 5)),
  candidate(45, 'professional.ai-automation-implementation', 'AI Automation Implementation', 'professional-creative-technical', 'complex-project', 'retain', 'Discovery-to-implementation project with integrations, data access, milestones, approvals, and ongoing support.', ['PROJECT_SCOPE', 'MILESTONE', 'NEGOTIABLE', 'CUSTOMER_ASSETS', 'CUSTOM_INTAKE', 'CONTRACT', 'REMOTE'], ['document-requirements', 'milestones', 'conditional-fulfillment', 'usage-pricing'], score(5, 5, 5, 5, 5, 5, 5, 5, 5, 5)),
]
