-- Keep test-mode commerce artifacts out of production financial reporting.
-- Stripe supplies `livemode` on Checkout Sessions, PaymentIntents, and webhook
-- events. Persist that immutable provenance beside every durable money record.
-- NULL means historical/unverified and must fail closed in live reporting.

alter table public.checkout_orders
  add column if not exists stripe_livemode boolean;

alter table public.agent_negotiations
  add column if not exists stripe_livemode boolean;

alter table public.checkout_sessions
  add column if not exists stripe_livemode boolean;

comment on column public.checkout_orders.stripe_livemode is
  'Stripe object livemode at settlement. TRUE is eligible for live financial reporting; FALSE is test; NULL is historical/unverified.';
comment on column public.agent_negotiations.stripe_livemode is
  'Stripe object livemode at escrow funding. TRUE is eligible for live financial reporting; FALSE is test; NULL is unfunded or historical/unverified.';
comment on column public.checkout_sessions.stripe_livemode is
  'Stripe PaymentIntent livemode recorded when an ACP/UCP session settles.';

create index if not exists checkout_orders_owner_live_created_idx
  on public.checkout_orders (owner_id, created_at desc)
  where stripe_livemode is true;

create index if not exists agent_negotiations_owner_live_created_idx
  on public.agent_negotiations (owner_id, created_at desc)
  where stripe_livemode is true;

-- The money-safety trigger's completion rule is a transition invariant. Its prior
-- definition also re-ran that rule when an already-complete row received an
-- unrelated metadata update, which blocked provenance, refund-ledger metadata,
-- and other harmless maintenance. Preserve every guard while applying the
-- completion check only when status actually enters `complete`.
create or replace function public.nz_negotiation_money_safety()
returns trigger
language plpgsql
set search_path to 'public', 'pg_temp'
as $$
begin
  if new.status = 'held' and new.stripe_payment_intent_id is null then
    raise exception 'negotiation %: cannot set held without a payment intent', new.id
      using errcode = 'check_violation';
  end if;

  if new.status = 'complete'
     and old.status is distinct from new.status
     and new.stripe_payment_intent_id is not null
     and coalesce(old.status, '') not in ('held', 'disputed')
     and coalesce(new.settlement_state, '') <> 'auto' then
    raise exception 'negotiation %: cannot complete a payment-backed negotiation without a captured hold', new.id
      using errcode = 'check_violation';
  end if;

  if new.status = 'agreement_proposed'
     and coalesce(old.status, '') in ('held', 'complete', 'declined', 'expired', 'refunded', 'disputed') then
    raise exception 'negotiation %: cannot reopen a closed/funded negotiation (% -> agreement_proposed)', new.id, old.status
      using errcode = 'check_violation';
  end if;

  if old.stripe_payment_intent_id is not null
     and new.amount_cents is distinct from old.amount_cents then
    raise exception 'negotiation %: amount_cents is locked once funding is attached', new.id
      using errcode = 'check_violation';
  end if;

  return new;
end;
$$;

-- These rows were generated by the 63-offer commerce gauntlet and point to
-- Stripe test-mode PaymentIntents. Mark only the deterministic seeded namespace;
-- every other historical row remains unverified until Stripe reconciliation.
update public.agent_negotiations
set stripe_livemode = false
where stripe_livemode is null
  and stripe_payment_intent_id is not null
  and (
    buyer_agent like 'SimBot-%'
    or slug like 'qa-neg-sim-%'
  );
