-- Buyer order portal. Buyers are ANONYMOUS to Nexez (no account) — their only prior
-- recourse was a `mailto:` on the checkout success page, and they had zero visibility
-- into refund/dispute status. This adds the durable bits a token-keyed buyer portal
-- (`/orders/<token>`) needs:
--   1. checkout_orders.access_token — the buyer's bearer credential for the portal,
--      generated by a column DEFAULT (so the webhook's upsert can't clobber it on a
--      re-delivery) + buyer_email (Stripe collected it; we threw it away) so we can
--      email a receipt + status updates. Mirrors the negotiation status_token pattern.
--   2. agent_negotiations.buyer_email — negotiation buyers already hold status_token
--      (their credential); this just lets us email them status updates too.
--   3. order_requests — buyer-originated recourse (refund request / problem report).
--      support_tickets is owner-RLS'd (insert requires auth.uid() = owner_id) so an
--      anonymous buyer can't write to it; this table is the buyer→seller channel,
--      written SERVICE-ROLE only (the token-gated /api/order-portal route), owner-read
--      like checkout_orders/billing_subscriptions (defense-in-depth vs the H1 class).
-- Additive + idempotent.

------------------------------------------------------------------------------
-- 1. checkout_orders: access_token (DB-default) + buyer_email
------------------------------------------------------------------------------
alter table public.checkout_orders
  add column if not exists buyer_email text,
  add column if not exists access_token text
    default (replace(gen_random_uuid()::text, '-', '') || replace(gen_random_uuid()::text, '-', ''));

-- Backfill any pre-existing rows that predate the default.
update public.checkout_orders
  set access_token = replace(gen_random_uuid()::text, '-', '') || replace(gen_random_uuid()::text, '-', '')
  where access_token is null;

create unique index if not exists checkout_orders_access_token_uidx
  on public.checkout_orders (access_token)
  where access_token is not null;

------------------------------------------------------------------------------
-- 2. agent_negotiations: buyer_email (status_token already the credential)
------------------------------------------------------------------------------
alter table public.agent_negotiations
  add column if not exists buyer_email text;

------------------------------------------------------------------------------
-- 3. order_requests: buyer-originated recourse
------------------------------------------------------------------------------
create table if not exists public.order_requests (
  id uuid primary key default gen_random_uuid(),
  -- which money path this request is about
  order_kind text not null check (order_kind in ('checkout', 'negotiation')),
  order_id uuid not null,
  owner_id uuid not null references auth.users(id) on delete cascade,
  page_id uuid references public.pages(id) on delete set null,
  slug text,
  buyer_email text,
  kind text not null check (kind in ('refund_request', 'problem_report')),
  message text,
  status text not null default 'open' check (status in ('open', 'acknowledged', 'resolved', 'declined')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists order_requests_owner_created_idx
  on public.order_requests (owner_id, created_at desc);
create index if not exists order_requests_order_idx
  on public.order_requests (order_kind, order_id);

-- At most ONE live (open/acknowledged) request of each kind per order — makes the
-- app-level dedup atomic (a racing duplicate hits 23505 instead of TOCTOU-inserting).
create unique index if not exists order_requests_one_live_per_kind_uidx
  on public.order_requests (order_kind, order_id, kind)
  where status in ('open', 'acknowledged');

create or replace function public.set_order_requests_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

alter function public.set_order_requests_updated_at() set search_path = '';

drop trigger if exists order_requests_set_updated_at on public.order_requests;
create trigger order_requests_set_updated_at
  before update on public.order_requests
  for each row
  execute function public.set_order_requests_updated_at();

alter table public.order_requests enable row level security;

-- Strip Supabase default grants (new public tables get ALL to anon+authenticated),
-- then re-grant only authenticated SELECT/UPDATE — the owner-scoped policies below
-- gate them. All INSERTs go through the service-role client (the token-gated route).
revoke all on public.order_requests from anon;
revoke all on public.order_requests from authenticated;
grant select, update on public.order_requests to authenticated;

drop policy if exists "Owners can read own order requests" on public.order_requests;
create policy "Owners can read own order requests"
  on public.order_requests
  for select
  to authenticated
  using ((select auth.uid()) = owner_id);

drop policy if exists "Owners can update own order requests" on public.order_requests;
create policy "Owners can update own order requests"
  on public.order_requests
  for update
  to authenticated
  using ((select auth.uid()) = owner_id)
  with check ((select auth.uid()) = owner_id);
