-- Nexez PR2 — Enterprise commercial terms
-- Server-controlled negotiated economics. Browser clients receive no access.

create table public.owner_commercial_terms (
  owner_id uuid primary key references auth.users(id) on delete cascade,
  commission_bps integer,
  effective_from timestamptz not null default now(),
  effective_until timestamptz,
  contract_reference text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null,

  constraint owner_commercial_terms_commission_bps_check
    check (commission_bps is null or commission_bps between 0 and 1000),

  constraint owner_commercial_terms_effective_window_check
    check (effective_until is null or effective_until > effective_from)
);

alter table public.owner_commercial_terms enable row level security;

revoke all on table public.owner_commercial_terms from public, anon, authenticated, service_role;
grant select, insert, update, delete on table public.owner_commercial_terms to service_role;

create policy "deny browser commercial terms access"
  on public.owner_commercial_terms
  for all
  to anon, authenticated
  using (false)
  with check (false);

create or replace function private.nz_touch_owner_commercial_terms_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $function$
begin
  new.updated_at := now();
  return new;
end;
$function$;

create trigger trg_owner_commercial_terms_updated_at
before update on public.owner_commercial_terms
for each row
execute function private.nz_touch_owner_commercial_terms_updated_at();


create table public.owner_commercial_terms_events (
  id bigint generated by default as identity primary key,
  owner_id uuid not null,
  actor_id uuid,
  action text not null
    check (action in ('insert', 'update', 'delete')),
  before_state jsonb not null default '{}'::jsonb,
  after_state jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.owner_commercial_terms_events enable row level security;

revoke all on table public.owner_commercial_terms_events from public, anon, authenticated, service_role;
revoke all on sequence public.owner_commercial_terms_events_id_seq from public, anon, authenticated, service_role;
grant select on table public.owner_commercial_terms_events to service_role;

create policy "deny browser commercial terms audit access"
  on public.owner_commercial_terms_events
  for all
  to anon, authenticated
  using (false)
  with check (false);

create index owner_commercial_terms_events_owner_created_idx
  on public.owner_commercial_terms_events (owner_id, created_at desc);

create or replace function private.nz_audit_owner_commercial_terms()
returns trigger
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_owner_id uuid;
  v_actor_id uuid;
begin
  if tg_op = 'DELETE' then
    v_owner_id := old.owner_id;
    v_actor_id := old.updated_by;

    insert into public.owner_commercial_terms_events (
      owner_id, actor_id, action, before_state, after_state
    )
    values (
      v_owner_id, v_actor_id, 'delete', to_jsonb(old), '{}'::jsonb
    );

    return old;
  elsif tg_op = 'INSERT' then
    v_owner_id := new.owner_id;
    v_actor_id := new.updated_by;

    insert into public.owner_commercial_terms_events (
      owner_id, actor_id, action, before_state, after_state
    )
    values (
      v_owner_id, v_actor_id, 'insert', '{}'::jsonb, to_jsonb(new)
    );

    return new;
  else
    v_owner_id := new.owner_id;
    v_actor_id := new.updated_by;

    insert into public.owner_commercial_terms_events (
      owner_id, actor_id, action, before_state, after_state
    )
    values (
      v_owner_id, v_actor_id, 'update', to_jsonb(old), to_jsonb(new)
    );

    return new;
  end if;
end;
$function$;

revoke all on function private.nz_touch_owner_commercial_terms_updated_at()
  from public, anon, authenticated, service_role;
revoke all on function private.nz_audit_owner_commercial_terms()
  from public, anon, authenticated, service_role;

create trigger trg_audit_owner_commercial_terms
after insert or update or delete on public.owner_commercial_terms
for each row
execute function private.nz_audit_owner_commercial_terms();

create or replace function private.nz_reject_owner_commercial_terms_event_mutation()
returns trigger
language plpgsql
security definer
set search_path = ''
as $function$
begin
  raise exception 'owner commercial terms events are append-only'
    using errcode = '55000';
end;
$function$;

revoke all on function private.nz_reject_owner_commercial_terms_event_mutation()
  from public, anon, authenticated, service_role;

create trigger trg_owner_commercial_terms_events_append_only
before update or delete on public.owner_commercial_terms_events
for each row
execute function private.nz_reject_owner_commercial_terms_event_mutation();

comment on table public.owner_commercial_terms is
  'Server-controlled owner commercial terms. Enterprise commission overrides live here; never use browser-supplied economics.';

comment on column public.owner_commercial_terms.commission_bps is
  'Negotiated Nexez platform commission in basis points. Database safety range 0-1000; application policy accepts Enterprise 100-200 bps.';

comment on table public.owner_commercial_terms_events is
  'Private append-only audit history for owner commercial-term changes.';
